from toontown.coghq.SpecImports import *
from toontown.toonbase import ToontownGlobals
CogParent = 10000
MidCogParent = 10021
FrontCogParent = 10061
BattleCellId = 0
MidBattleCellId = 1
FrontBattleCellId = 2
BattleCells = {BattleCellId: {'parentEntId': CogParent,
                'pos': Point3(0, 0, 0)},
 MidBattleCellId: {'parentEntId': MidCogParent,
                   'pos': Point3(0, 0, 0)},
 FrontBattleCellId: {'parentEntId': FrontCogParent,
                     'pos': Point3(0, 0, 0)}}
CogData = [{'parentEntId': CogParent,
  'boss': 0,
  'level': 11,
  'battleCell': BattleCellId,
  'pos': Point3(-8, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'gold': 0,
  'skeleton': 1},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 7,
  'battleCell': BattleCellId,
  'pos': Point3(-4, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'gold': 1,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 11,
  'battleCell': BattleCellId,
  'pos': Point3(0, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'gold': 0,
  'skeleton': 1},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 7,
  'battleCell': BattleCellId,
  'pos': Point3(4, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'gold': 1,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 6,
  'battleCell': BattleCellId,
  'pos': Point3(8, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'gold': 1,
  'skeleton': 0},
 {'parentEntId': MidCogParent,
  'boss': 0,
  'level': 10,
  'battleCell': MidBattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': MidCogParent,
  'boss': 0,
  'level': 7,
  'battleCell': MidBattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'gold': 1,
  'skeleton': 0},
 {'parentEntId': MidCogParent,
  'boss': 0,
  'level': 11,
  'battleCell': MidBattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': MidCogParent,
  'boss': 0,
  'level': 12,
  'battleCell': MidBattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': FrontCogParent,
  'boss': 0,
  'level': 10,
  'battleCell': FrontBattleCellId,
  'pos': Point3(-4, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'gold': 1,
  'skeleton': 0},
 {'parentEntId': FrontCogParent,
  'boss': 0,
  'level': 13,
  'battleCell': FrontBattleCellId,
  'pos': Point3(0, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': FrontCogParent,
  'boss': 0,
  'level': 12,
  'battleCell': FrontBattleCellId,
  'pos': Point3(4, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0}]
ReserveCogData = []
