# BOSSBOT DEPARTMENT
FLUNKY = 'f'
PENCIL_PUSHER = 'p'
YESMAN = 'ym'
MICROMANAGER = 'mm'
DOWNSIZER = 'ds'
HEAD_HUNTER = 'hh'
CORPORATE_RAIDER = 'cr'
THE_BIG_CHEESE = 'tbc'
THE_CLUB_PRESIDENT = 'clmp'
BOSSBOT = 'c'

# LAWBOT DEPARTMENT
BOTTOM_FEEDER = 'bf'
BLOODSUCKER = 'b'
DOUBLE_TALKER = 'dt'
AMBULANCE_CHASER = 'ac'
ATTORNEY = 'att'
BACK_STABBER = 'bs'
SPIN_DOCTOR = 'sd'
LEGAL_EAGLE = 'le'
BARRISTER = 'barr'
BIG_WIG = 'bw'
THE_OFFICE_CLERK = 'ofck'
LAWBOT = 'l'

# CASHBOT DEPARTMENT
SHORT_CHANGE = 'sc'
PENNY_PINCHER = 'pp'
TIGHTWAD = 'tw'
BEAN_COUNTER = 'bc'
NUMBER_CRUNCHER = 'nc'
MONEY_BAGS = 'mb'
LOAN_SHARK = 'ls'
ROBBER_BARON = 'rb'
THE_MINT_AUDITOR = 'maud'
CASHBOT = 'm'

# SELLBOT DEPARTMENT
COLD_CALLER = 'cc'
TELEMARKETER = 'tm'
NAME_DROPPER = 'nd'
GLAD_HANDER = 'gh'
MOVER_AND_SHAKER = 'ms'
TWO_FACE = 'tf'
THE_MINGLER = 'm'
MR_HOLLYWOOD = 'mh'
THE_FACTORY_FOREMAN = 'ffor'
SELLBOT = 's'

# RESOURCEBOT DEPARTMENT
BARISTA = 'bar'
DESK_JOCKY = 'djoc'
RULE_BENDER = 'rben'
ADVENTURE_COACH = 'advc'
REPRESENTATIVE = 'repr'
CROWD_CONTROL = 'crdc'
INVESTIGATOR = 'inv'
CONFISCATOR = 'cfn'
THE_HEAD_REPRESENTATIVE = 'hrep'
RESOURCEBOT = 'r'

EMPLOYEE_SELLBOTS = [COLD_CALLER, TELEMARKETER, NAME_DROPPER, GLAD_HANDER, MOVER_AND_SHAKER, TWO_FACE, THE_MINGLER, MR_HOLLYWOOD]
EMPLOYEE_CASHBOTS = [SHORT_CHANGE, PENNY_PINCHER, TIGHTWAD, BEAN_COUNTER, NUMBER_CRUNCHER, MONEY_BAGS, LOAN_SHARK, ROBBER_BARON]
EMPLOYEE_LAWBOTS = [BOTTOM_FEEDER, BLOODSUCKER, DOUBLE_TALKER, AMBULANCE_CHASER, ATTORNEY, BACK_STABBER, SPIN_DOCTOR, LEGAL_EAGLE, BARRISTER, BIG_WIG]
EMPLOYEE_BOSSBOTS = [FLUNKY, PENCIL_PUSHER, YESMAN, MICROMANAGER, DOWNSIZER, HEAD_HUNTER, CORPORATE_RAIDER, THE_BIG_CHEESE]
EMPLOYEE_RESOURCEBOTS = [BARISTA, INVESTIGATOR, CONFISCATOR]

EXTRA_COGS = {
    's': [THE_FACTORY_FOREMAN,],
    'm': [THE_MINT_AUDITOR,],
    'l': [ATTORNEY, BARRISTER, THE_OFFICE_CLERK],
    'c': [THE_CLUB_PRESIDENT,],
    'r': [THE_HEAD_REPRESENTATIVE,],
}

suitHeadTypes = [
    FLUNKY,
    PENCIL_PUSHER,
    YESMAN,
    MICROMANAGER,
    DOWNSIZER,
    HEAD_HUNTER,
    CORPORATE_RAIDER,
    THE_BIG_CHEESE,
    BOTTOM_FEEDER,
    BLOODSUCKER,
    DOUBLE_TALKER,
    AMBULANCE_CHASER,
    BACK_STABBER,
    SPIN_DOCTOR,
    LEGAL_EAGLE,
    BIG_WIG,
    SHORT_CHANGE,
    PENNY_PINCHER,
    TIGHTWAD,
    BEAN_COUNTER,
    NUMBER_CRUNCHER,
    MONEY_BAGS,
    LOAN_SHARK,
    ROBBER_BARON,
    COLD_CALLER,
    TELEMARKETER,
    NAME_DROPPER,
    GLAD_HANDER,
    MOVER_AND_SHAKER,
    TWO_FACE,
    THE_MINGLER,
    MR_HOLLYWOOD,
    BARISTA,
    INVESTIGATOR,
    CONFISCATOR,
    THE_FACTORY_FOREMAN,
    THE_MINT_AUDITOR,
    THE_OFFICE_CLERK,
    THE_CLUB_PRESIDENT,
    BARRISTER,
    ATTORNEY,
]