from toontown.toonbase import TTLocalizer
from toontown.coghq.SpecImports import *
GlobalEntities = {1000: {'type': 'levelMgr',
        'name': 'LevelMgr',
        'comment': '',
        'parentEntId': 0,
        'cogLevel': 0,
        'farPlaneDistance': 1500.0,
        'modelFilename': 'phase_10/models/cashbotHQ/ttr_m_ara_chq_mintZone03a',
        'wantDoors': 1},
 1001: {'type': 'editMgr',
        'name': 'EditMgr',
        'parentEntId': 0,
        'insertEntity': None,
        'removeEntity': None,
        'requestNewEntity': None,
        'requestSave': None},
 0: {'type': 'zone',
     'name': 'UberZone',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': '',
     'visibility': []},
 10001: {'type': 'model',
      'name': 'room',
      'comment': '',
      'parentEntId': 0,
      'pos': Point3(0.0, 1000, 0.0),
      'hpr': Vec3(0.0, 0.0, 0.0),
      'scale': Vec3(1.0, 1.0, 1.0),
      'collisionsOnly': 0,
      'flattenType': 'light',
      'loadType': 'loadModelCopy',
      'modelPath': 'phase_9/models/cogHQ/ttr_m_ara_shq_factoryZone04'},
 10002: {'type': 'model',
      'name': 'room',
      'comment': '',
      'parentEntId': 0,
      'pos': Point3(0.0, 1000, 0.0),
      'hpr': Vec3(0.0, 0.0, 0.0),
      'scale': Vec3(1.0, 1.0, 1.0),
      'collisionsOnly': 0,
      'flattenType': 'light',
      'loadType': 'loadModelCopy',
      'modelPath': 'phase_9/models/cogHQ/ttr_m_ara_shq_factoryZone07'},
 10003: {'type': 'model',
      'name': 'room',
      'comment': '',
      'parentEntId': 0,
      'pos': Point3(0.0, 1000, 0.0),
      'hpr': Vec3(0.0, 0.0, 0.0),
      'scale': Vec3(1.0, 1.0, 1.0),
      'collisionsOnly': 0,
      'flattenType': 'light',
      'loadType': 'loadModelCopy',
      'modelPath': 'phase_9/models/cogHQ/ttr_m_ara_shq_factoryZone10'},
 10004: {'type': 'model',
      'name': 'room',
      'comment': '',
      'parentEntId': 0,
      'pos': Point3(0.0, 1000, 0.0),
      'hpr': Vec3(0.0, 0.0, 0.0),
      'scale': Vec3(1.0, 1.0, 1.0),
      'collisionsOnly': 0,
      'flattenType': 'light',
      'loadType': 'loadModelCopy',
      'modelPath': 'phase_9/models/cogHQ/ttr_m_ara_shq_factoryZone09'},
 10005: {'type': 'model',
      'name': 'room',
      'comment': '',
      'parentEntId': 0,
      'pos': Point3(0.0, 1000, 0.0),
      'hpr': Vec3(0.0, 0.0, 0.0),
      'scale': Vec3(1.0, 1.0, 1.0),
      'collisionsOnly': 0,
      'flattenType': 'light',
      'loadType': 'loadModelCopy',
      'modelPath': 'phase_9/models/cogHQ/ttr_m_ara_shq_factoryZone21'},
                  10006: {'type': 'model',
                          'name': 'room',
                          'comment': '',
                          'parentEntId': 0,
                          'pos': Point3(0.0, 1000, 0.0),
                          'hpr': Vec3(0.0, 0.0, 0.0),
                          'scale': Vec3(1.0, 1.0, 1.0),
                          'collisionsOnly': 0,
                          'flattenType': 'light',
                          'loadType': 'loadModelCopy',
                          'modelPath': 'phase_9/models/cogHQ/ttr_m_ara_shq_factoryZone04'},
                  10007: {'type': 'model',
                          'name': 'room',
                          'comment': '',
                          'parentEntId': 0,
                          'pos': Point3(0.0, 1000, 0.0),
                          'hpr': Vec3(0.0, 0.0, 0.0),
                          'scale': Vec3(1.0, 1.0, 1.0),
                          'collisionsOnly': 0,
                          'flattenType': 'light',
                          'loadType': 'loadModelCopy',
                          'modelPath': 'phase_9/models/cogHQ/ttr_m_ara_shq_factoryZone07'},
                  10008: {'type': 'model',
                          'name': 'room',
                          'comment': '',
                          'parentEntId': 0,
                          'pos': Point3(0.0, 1000, 0.0),
                          'hpr': Vec3(0.0, 0.0, 0.0),
                          'scale': Vec3(1.0, 1.0, 1.0),
                          'collisionsOnly': 0,
                          'flattenType': 'light',
                          'loadType': 'loadModelCopy',
                          'modelPath': 'phase_9/models/cogHQ/ttr_m_ara_shq_factoryZone13a'},
                  10009: {'type': 'model',
                          'name': 'room',
                          'comment': '',
                          'parentEntId': 0,
                          'pos': Point3(0.0, 1000, 0.0),
                          'hpr': Vec3(0.0, 0.0, 0.0),
                          'scale': Vec3(1.0, 1.0, 1.0),
                          'collisionsOnly': 0,
                          'flattenType': 'light',
                          'loadType': 'loadModelCopy',
                          'modelPath': 'phase_9/models/cogHQ/ttr_m_ara_shq_factoryZone09'},
                  100010: {'type': 'model',
                          'name': 'room',
                          'comment': '',
                          'parentEntId': 0,
                          'pos': Point3(0.0, 1000, 0.0),
                          'hpr': Vec3(0.0, 0.0, 0.0),
                          'scale': Vec3(1.0, 1.0, 1.0),
                          'collisionsOnly': 0,
                          'flattenType': 'light',
                          'loadType': 'loadModelCopy',
                          'modelPath': 'phase_9/models/cogHQ/ttr_m_ara_shq_factoryZone21'},
                  100011: {'type': 'model',
                          'name': 'room',
                          'comment': '',
                          'parentEntId': 0,
                          'pos': Point3(0.0, 1000, 0.0),
                          'hpr': Vec3(0.0, 0.0, 0.0),
                          'scale': Vec3(1.0, 1.0, 1.0),
                          'collisionsOnly': 0,
                          'flattenType': 'light',
                          'loadType': 'loadModelCopy',
                          'modelPath': 'phase_9/models/cogHQ/ttr_m_ara_shq_factoryZone21'},
                  }
Scenario0 = {}
levelSpec = {'globalEntities': GlobalEntities,
 'scenarios': [Scenario0]}
