from .SpecImports import *
from toontown.toonbase import ToontownGlobals
CogParent = 24200
CogParent2 = 24201
CogParent3 = 24202
BattlePlace1 = 24200
BattlePlace2 = 24201
BattlePlace3 = 24202
BattleCellId = 0
BattleCellId2 = 1
BattleCellId3 = 2
BattleCells = {BattleCellId: {'parentEntId': BattlePlace1,
                'pos': Point3(0, 0, 0)},
               BattleCellId2: {'parentEntId': BattlePlace2,
                'pos': Point3(0, 0, 0)},
               BattleCellId3: {'parentEntId': BattlePlace3,
                'pos': Point3(0, 0, 0)}}
CogData = [{'parentEntId': CogParent,
  'boss': 0,
  'level': 13,
  'battleCell': BattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 12,
  'battleCell': BattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 10,
  'battleCell': BattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 12,
  'battleCell': BattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
   {'parentEntId': CogParent2,
    'boss': 0,
    'level': 13,
    'battleCell': BattleCellId2,
    'pos': Point3(-6, 0, 0),
    'h': 180,
    'behavior': 'stand',
    'path': None,
    'skeleton': 0},
   {'parentEntId': CogParent2,
    'boss': 0,
    'level': 12,
    'battleCell': BattleCellId2,
    'pos': Point3(-2, 0, 0),
    'h': 180,
    'behavior': 'stand',
    'path': None,
    'skeleton': 0},
   {'parentEntId': CogParent2,
    'boss': 0,
    'level': 10,
    'battleCell': BattleCellId2,
    'pos': Point3(2, 0, 0),
    'h': 180,
    'behavior': 'stand',
    'path': None,
    'skeleton': 0},
   {'parentEntId': CogParent2,
    'boss': 0,
    'level': 12,
    'battleCell': BattleCellId2,
    'pos': Point3(6, 0, 0),
    'h': 180,
    'behavior': 'stand',
    'path': None,
    'skeleton': 0},
{'parentEntId': CogParent3,
  'boss': 0,
  'level': 13,
  'battleCell': BattleCellId3,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent3,
  'boss': 0,
  'level': 12,
  'battleCell': BattleCellId3,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent3,
  'boss': 0,
  'level': 10,
  'battleCell': BattleCellId3,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent3,
  'boss': 0,
  'level': 12,
  'battleCell': BattleCellId3,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0}
           ]
ReserveCogData = []
