from toontown.coghq.SpecImports import *
GlobalEntities = {1000: {'type': 'levelMgr', 'name': 'UberZone', 'comment': '', 'parentEntId': 0, 'cogLevel': 0, 'farPlaneDistance': 1500, 'modelFilename': 'phase_12/models/bossbotHQ/ttr_m_ara_bhq_cgcZone12a', 'wantDoors': 1}, 1001: {'type': 'editMgr', 'name': 'EditMgr', 'parentEntId': 0, 'insertEntity': None, 'removeEntity': None, 'requestNewEntity': None, 'requestSave': None}, 0: {'type': 'zone', 'name': 'UberZone', 'comment': '', 'parentEntId': 0, 'scale': LVecBase3f(1, 1, 1), 'description': '', 'visibility': []}, 110200: {'type': 'battleBlocker', 'name': '<unnamed>', 'comment': '', 'parentEntId': 0, 'pos': LPoint3f(-51.1894, 52.6959, 0), 'hpr': LVecBase3f(180, 0, 0), 'scale': LVecBase3f(1, 1, 1), 'cellId': 0, 'radius': 10}, 110800: {'type': 'battleBlocker', 'name': '<unnamed>', 'comment': '', 'parentEntId': 0, 'pos': LPoint3f(14.5304, 0, 0), 'hpr': LVecBase3f(270, 0, 0), 'scale': LVecBase3f(1, 1, 1), 'cellId': 1, 'radius': 10}, 10002: {'type': 'nodepath', 'name': 'props', 'comment': '', 'parentEntId': 0, 'pos': LPoint3f(0, 0, 0), 'hpr': LVecBase3f(0, 0, 0), 'scale': LVecBase3f(1, 1, 1)}, 110001: {'type': 'nodepath', 'name': '<unnamed>', 'comment': '', 'parentEntId': 0, 'pos': LPoint3f(101.07, 0, 0), 'hpr': LVecBase3f(270, 0, 0), 'scale': LVecBase3f(1, 1, 1)}, 12100: {'type': 'model', 'name': 'middle', 'comment': '', 'parentEntId': 0, 'pos': LPoint3f(-50.086, 0, 0), 'hpr': LVecBase3f(0, 0, 0), 'scale': LVecBase3f(1.6, 1.6, 1.6), 'collisionsOnly': 0, 'flattenType': 'light', 'loadType': 'loadModelCopy', 'modelPath': 'phase_12/models/bossbotHQ/ttr_m_ara_bhq_cgcCentersectionSpearhead.bam'}, 12101: {'type': 'model', 'name': 'middle', 'comment': '', 'parentEntId': 0, 'pos': LPoint3f(25.3435, 70.2252, 0), 'hpr': LVecBase3f(270, 0, 0), 'scale': LVecBase3f(0.42, 0.42, 0.42), 'collisionsOnly': 0, 'flattenType': 'light', 'loadType': 'loadModelCopy', 'modelPath': 'phase_12/models/bossbotHQ/ttr_m_ara_bhq_clubHouse.bam'}, 12102: {'type': 'model', 'name': 'middle', 'comment': '', 'parentEntId': 0, 'pos': LPoint3f(13.9283, -49.7444, 0), 'hpr': LVecBase3f(0, 0, 0), 'scale': LVecBase3f(1, 1, 1), 'collisionsOnly': 0, 'flattenType': 'light', 'loadType': 'loadModelCopy', 'modelPath': 'phase_12/models/bossbotHQ/ttr_m_ara_bhq_cogThinTree2.bam'}, 12103: {'type': 'model', 'name': 'middle', 'comment': '', 'parentEntId': 0, 'pos': LPoint3f(3.28564, -47.2114, 0), 'hpr': LVecBase3f(0, 0, 0), 'scale': LVecBase3f(1.4, 1.4, 1.4), 'collisionsOnly': 0, 'flattenType': 'light', 'loadType': 'loadModelCopy', 'modelPath': 'phase_12/models/bossbotHQ/ttr_m_ara_bhq_cogThinTree2.bam'}, 12104: {'type': 'model', 'name': 'middle', 'comment': '', 'parentEntId': 0, 'pos': LPoint3f(0, -43.1823, 0), 'hpr': LVecBase3f(0, 0, 0), 'scale': LVecBase3f(5, 5, 5), 'collisionsOnly': 0, 'flattenType': 'light', 'loadType': 'loadModelCopy', 'modelPath': 'phase_12/models/bossbotHQ/ttr_m_ara_bhq_cogGolfFlag.bam'}}


#ttr_m_ara_bhq_cogGolfFlag

#ttr_m_ara_bhq_cogThinTree2

Scenario0 = {}
levelSpec = {'globalEntities': GlobalEntities,
 'scenarios': [Scenario0]}
