from toontown.coghq.SpecImports import *
from toontown.coghq.SpecImports import *
import random
GlobalEntities = {1000: {'type': 'levelMgr', 'name': 'UberZone', 'comment': '', 'parentEntId': 0, 'cogLevel': 0, 'farPlaneDistance': 1500, 'modelFilename': 'phase_11/models/lawbotHQ/ttr_m_ara_lhq_daLobby', 'wantDoors': 1}, 1001: {'type': 'editMgr', 'name': 'EditMgr', 'parentEntId': 0, 'insertEntity': None, 'removeEntity': None, 'requestNewEntity': None, 'requestSave': None}, 0: {'type': 'zone', 'name': 'UberZone', 'comment': '', 'parentEntId': 0, 'scale': LVecBase3f(1, 1, 1), 'description': '', 'visibility': []}, 100020: {'type': 'healBarrel', 'name': '<unnamed>', 'comment': '', 'parentEntId': 0, 'pos': LPoint3f(144.808, 63.558, 51.6751), 'hpr': LVecBase3f(262.761, 0, 0), 'scale': 1, 'rewardPerGrab': 10, 'rewardPerGrabMax': 0}, 100019: {'type': 'healBarrel', 'name': '<unnamed>', 'comment': '', 'parentEntId': 0, 'pos': LPoint3f(144.81, 67.72, 51.68), 'hpr': LVecBase3f(299.197, 0, 0), 'scale': 1, 'rewardPerGrab': 10, 'rewardPerGrabMax': 0}, 100018: {'type': 'healBarrel', 'name': '<unnamed>', 'comment': '', 'parentEntId': 0, 'pos': LPoint3f(144.81, 65.6698, 55.7619), 'hpr': LVecBase3f(-90, 0, 0), 'scale': 1, 'rewardPerGrab': 10, 'rewardPerGrabMax': 0}, 1000777: {'type': 'model', 'name': '<unnamed>', 'comment': '', 'modelPart': '**/LegalIcon', 'parentEntId': 0, 'pos': LPoint3f(86.8216, 92.7527, 61.3929), 'hpr': LVecBase3f(0, 0, 0), 'scale': LVecBase3f(3, 3, 3), 'collisionsOnly': 0, 'flattenType': 'light', 'loadType': 'loadModelCopy', 'modelPath': 'phase_3.5/models/props/ttr_m_ara_gen_cogIcons'}, 1000778: {'type': 'model', 'name': '<unnamed>', 'comment': '', 'modelPart': '**/LegalIcon', 'parentEntId': 0, 'pos': LPoint3f(130.193, 92.75, 61.39), 'hpr': LVecBase3f(0, 0, 0), 'scale': LVecBase3f(3, 3, 3), 'collisionsOnly': 0, 'flattenType': 'light', 'loadType': 'loadModelCopy', 'modelPath': 'phase_3.5/models/props/ttr_m_ara_gen_cogIcons'}, 1000779: {'type': 'model', 'name': '<unnamed>', 'comment': '', 'modelPart': '**/geo_M_ToughLegalIcon_01', 'parentEntId': 0, 'pos': LPoint3f(130.19, 92.7732, 61.39), 'hpr': LVecBase3f(0, 0, 0), 'scale': LVecBase3f(1.2, 1.2, 1.2), 'collisionsOnly': 0, 'flattenType': 'light', 'loadType': 'loadModelCopy', 'modelPath': 'phase_3.5/models/props/ttr_m_ara_gen_cogToughIcons'}}

Scenario0 = {}
levelSpec = {'globalEntities': GlobalEntities,
 'scenarios': [Scenario0],
 'titleString': 'MemTag: LawbotOfficeEntrance_Action00 %s' % random.random()}
