from .SpecImports import *
LobbyParent = 10014
BoilerParent = 10030
PipeLeftParent = 10023
PipeRightParent = 10032
OilParent = 10034
ControlParent = 10037
DuctParent = 10036
CenterSiloBattleCellParent = 10064
CenterSiloParent = 20095
SigRoomParent = 20058
WestSiloParent = 20094
WestSiloBattleCellParent = 10047
EastSiloParent = 20096
EastSiloBattleCellParent = 10068
LobbyCell = 0
BoilerCell = 1
PipeLeftCell = 2
PipeRightCell = 3
OilCell = 4
ControlCell = 5
DuctCell = 6
CenterSiloCell = 7
SigRoomCell = 8
WestSiloCell = 9
EastSiloCell = 10
BattleCells = {LobbyCell: {'parentEntId': LobbyParent,
             'pos': Point3(0, 0, 0)},
 BoilerCell: {'parentEntId': BoilerParent,
              'pos': Point3(0, 0, 0)},
 OilCell: {'parentEntId': OilParent,
           'pos': Point3(0, 0, 0)},
 ControlCell: {'parentEntId': ControlParent,
               'pos': Point3(0, 0, 0)},
 CenterSiloCell: {'parentEntId': CenterSiloBattleCellParent,
                  'pos': Point3(0, 0, 0)},
 PipeLeftCell: {'parentEntId': PipeLeftParent,
                'pos': Point3(0, 0, 0)},
 PipeRightCell: {'parentEntId': PipeRightParent,
                 'pos': Point3(0, 0, 0)},
 DuctCell: {'parentEntId': DuctParent,
            'pos': Point3(0, 0, 0)},
 SigRoomCell: {'parentEntId': SigRoomParent,
               'pos': Point3(0, 0, 0)},
 WestSiloCell: {'parentEntId': WestSiloBattleCellParent,
                'pos': Point3(0, 0, 0)},
 EastSiloCell: {'parentEntId': EastSiloBattleCellParent,
                'pos': Point3(-20, -10, 0)}}
CogData = [{'type': 'cc',
  'parentEntId': LobbyParent,
  'boss': 0,
  'suitName': 'bar',
  'level': random.randint(5, 6),
  'battleCell': LobbyCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20078,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': LobbyParent,
  'boss': 0,
  'level': random.randint(8, 10),
  'battleCell': LobbyCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20009,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': LobbyParent,
  'boss': 1,
  'suitName': THE_FACTORY_FOREMAN,
  'level': 35,
  'battleCell': LobbyCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'tm',
  'parentEntId': LobbyParent,
  'boss': 0,
  'level': random.randint(5, 6),
  'battleCell': LobbyCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20079,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'cc',
  'parentEntId': BoilerParent,
  'boss': 0,
  'level': random.randint(5, 6),
  'battleCell': BoilerCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'walk',
  'path': 20076,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': BoilerParent,
  'boss': 0,
  'suitName': random.choice(['cfn', 'nc']),
  'level': random.randint(8, 10),
  'battleCell': BoilerCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'walk',
  'path': 20077,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': BoilerParent,
  'boss': 0,
  'level': random.randint(10, 12),
  'battleCell': BoilerCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': OilParent,
  'boss': 0,
  'level': random.randint(5, 7),
  'battleCell': OilCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 60133,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': OilParent,
  'boss': 0,
  'level': random.randint(8, 10),
  'battleCell': OilCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 60134,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': OilParent,
  'boss': 0,
  'level': random.randint(8, 10),
  'battleCell': OilCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 60135,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'cc',
  'parentEntId': ControlParent,
  'boss': 0,
  'level': random.randint(8, 10),
  'battleCell': ControlCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20039,
  'skeleton': 1},
 {'type': 'cc',
  'parentEntId': ControlParent,
  'boss': 0,
  'level': random.randint(10, 12),
  'battleCell': ControlCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20049,
  'skeleton': 1},
 {'type': 'cc',
  'parentEntId': ControlParent,
  'boss': 0,
  'level': random.randint(8, 10),
  'battleCell': ControlCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20075,
  'skeleton': 1},
 {'type': 'tm',
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'suitName': random.choice(['cfn', 'nc']),
  'level': random.randint(10, 12),
  'battleCell': CenterSiloCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20103,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'gh',
  'parentEntId': CenterSiloParent,
  'boss': 1,
  'suitName': 'trf',
  'level': 20,
  'battleCell': CenterSiloCell,
  'pos': Point3(0, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'tm',
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': random.randint(10, 12),
  'battleCell': CenterSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20104,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': random.randint(10, 12),
  'battleCell': CenterSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20105,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': WestSiloParent,
  'boss': 0,
  'suitName': 'inv',
  'level': random.randint(10, 12),
  'battleCell': WestSiloCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20097,
  'skeleton': 0},
 {'type': 'gh',
  'parentEntId': WestSiloParent,
  'boss': 0,
  'level': random.randint(10, 12),
  'battleCell': WestSiloCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20098,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': WestSiloParent,
  'boss': 0,
  'level': random.randint(10, 12),
  'battleCell': WestSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20099,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': EastSiloParent,
  'boss': 0,
  'level': random.randint(10, 12),
  'battleCell': EastSiloCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20100,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'gh',
  'parentEntId': EastSiloParent,
  'boss': 0,
  'suitName': random.choice(['cfn', 'ac', 'ds', 'ms']),
  'level': random.randint(9, 11),
  'battleCell': EastSiloCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20101,
  'skeleton': 0},
 {'type': 'tm',
  'parentEntId': EastSiloParent,
  'boss': 0,
  'level': random.randint(10, 12),
  'battleCell': EastSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20102,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': PipeLeftParent,
  'boss': 0,
  'level': random.randint(8, 10),
  'battleCell': PipeLeftCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20109,
  'skeleton': 1},
 {'type': 'tm',
  'parentEntId': PipeLeftParent,
  'boss': 0,
  'level': random.randint(5, 7),
  'battleCell': PipeLeftCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20110,
  'skeleton': 1},
 {'type': 'tm',
  'parentEntId': PipeLeftParent,
  'boss': 0,
  'level': random.randint(5, 7),
  'battleCell': PipeLeftCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20111,
  'skeleton': 1},
 {'type': 'tm',
  'parentEntId': PipeRightParent,
  'boss': 0,
  'level': random.randint(5, 7),
  'battleCell': PipeRightCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20106,
  'skeleton': 1},
 {'type': 'tm',
  'parentEntId': PipeRightParent,
  'boss': 0,
  'level': random.randint(8, 10),
  'battleCell': PipeRightCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20107,
  'skeleton': 1},
 {'type': 'tm',
  'parentEntId': PipeRightParent,
  'boss': 0,
  'level': random.randint(5, 7),
  'battleCell': PipeRightCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20108,
  'skeleton': 1},
 {'type': 'cc',
  'parentEntId': DuctParent,
  'boss': 0,
  'level': random.randint(5, 6),
  'battleCell': DuctCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20038,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': DuctParent,
  'boss': 0,
  'level': random.randint(8, 10),
  'battleCell': DuctCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20067,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': DuctParent,
  'boss': 0,
  'level': random.randint(5, 7),
  'battleCell': DuctCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20068,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': SigRoomParent,
  'boss': 0,
  'level': random.randint(5, 7),
  'battleCell': SigRoomCell,
  'pos': Point3(5, -10.75, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': SigRoomParent,
  'boss': 0,
  'level': random.randint(8, 10),
  'battleCell': SigRoomCell,
  'pos': Point3(5, -3.25, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': SigRoomParent,
  'boss': 0,
  'level': random.randint(5, 7),
  'battleCell': SigRoomCell,
  'pos': Point3(5, 3.25, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': SigRoomParent,
  'boss': 0,
  'level': random.randint(10, 12),
  'battleCell': SigRoomCell,
  'pos': Point3(5, 10.75, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': random.choice([0, 0, 0, 1])}]
ReserveCogData = [{'type': 'cc',
  'parentEntId': LobbyParent,
  'boss': 0,
  'level': 2,
  'battleCell': LobbyCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20009,
  'skeleton': random.choice([0, 0, 0, 1]),
  'joinParent': 20018},
 {'type': 'cc',
  'parentEntId': BoilerParent,
  'boss': 0,
  'level': 2,
  'battleCell': BoilerCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'walk',
  'path': 20076,
  'skeleton': random.choice([0, 0, 0, 1]),
  'joinParent': 20019},
 {'type': 'tm',
  'parentEntId': BoilerParent,
  'boss': 0,
  'level': 2,
  'battleCell': BoilerCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'walk',
  'path': 20077,
  'skeleton': random.choice([0, 0, 0, 1]),
  'joinParent': 20019},
 {'type': 'tm',
  'parentEntId': OilParent,
  'boss': 0,
  'level': random.randint(5, 6),
  'battleCell': OilCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 60133,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': OilParent,
  'boss': 0,
  'level': random.randint(5, 7),
  'battleCell': OilCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 60135,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'cc',
  'parentEntId': ControlParent,
  'boss': 0,
  'level': 2,
  'battleCell': ControlCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20039,
  'skeleton': 1},
 {'type': 'cc',
  'parentEntId': ControlParent,
  'boss': 0,
  'level': 2,
  'battleCell': ControlCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20049,
  'skeleton': 1},
 {'type': 'cc',
  'parentEntId': ControlParent,
  'boss': 0,
  'level': 2,
  'battleCell': ControlCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'walk',
  'path': 20075,
  'skeleton': 1},
 {'type': 'tm',
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': random.randint(5, 6),
  'battleCell': CenterSiloCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20103,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'gh',
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': random.randint(8, 10),
  'battleCell': CenterSiloCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': random.randint(5, 6),
  'battleCell': CenterSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20104,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': random.randint(5, 6),
  'battleCell': CenterSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20105,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': PipeLeftParent,
  'boss': 0,
  'level': random.randint(5, 6),
  'battleCell': PipeLeftCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': 1},
 {'type': 'tm',
  'parentEntId': PipeLeftParent,
  'boss': 0,
  'level': random.randint(5, 7),
  'battleCell': PipeLeftCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': 1},
 {'type': 'tm',
  'parentEntId': PipeRightParent,
  'boss': 0,
  'level': random.randint(5, 6),
  'battleCell': PipeRightCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': 1},
 {'type': 'tm',
  'parentEntId': PipeRightParent,
  'boss': 0,
  'level': random.randint(5, 7),
  'battleCell': PipeRightCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': 1},
 {'type': 'cc',
  'parentEntId': DuctParent,
  'boss': 0,
  'level': 2,
  'battleCell': DuctCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20038,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': DuctParent,
  'boss': 0,
  'level': 2,
  'battleCell': DuctCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20067,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': SigRoomParent,
  'boss': 0,
  'level': random.randint(5, 6),
  'battleCell': SigRoomCell,
  'pos': Point3(5, -10.75, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': random.choice([0, 0, 0, 1])},
 {'type': 'tm',
  'parentEntId': SigRoomParent,
  'boss': 0,
  'level': random.randint(5, 7),
  'battleCell': SigRoomCell,
  'pos': Point3(5, -3.25, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': random.choice([0, 0, 0, 1])}]
