from toontown.coghq.SpecImports import *
GlobalEntities = {1000: {'type': 'levelMgr',
        'name': 'LevelMgr',
        'comment': '',
        'parentEntId': 0,
        'cogLevel': 0,
        'farPlaneDistance': 1500,
        'modelFilename': 'phase_4/models/neighborhoods/toontown_central',
        'wantDoors': 1},
 1001: {'type': 'editMgr',
        'name': 'EditMgr',
        'parentEntId': 0,
        'insertEntity': None,
        'removeEntity': None,
        'requestNewEntity': None,
        'requestSave': None},
 0: {'type': 'zone',
     'name': 'UberZone',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': '',
     'visibility': []},
}

"""
2001: {'type': 'cogDummy',
   'name': 'cogDumbo',
   'comment': '',
   'pos': Point3(0, 0, 0),
   'hpr': Vec3(0, 0, 0),
   'parentEntId': 0,
   'scale': 1,
   'description': '',
   'zoneId': 2000,
        }
"""