from .SpecImports import *
from toontown.toonbase import ToontownGlobals
CogParent = 10001
CogParent2 = 64001
CogParent3 = 64002
CogParent4 = 64003
BattleCellId = 0
BattleCellId2 = 1
BattleCellId3 = 2
BattleCellId4 = 3
BattleCells = {BattleCellId: {'parentEntId': CogParent,
                'pos': Point3(0, 0, 0)},
               BattleCellId2: {'parentEntId': CogParent2,
                'pos': Point3(0, 0, 0)},
               BattleCellId3: {'parentEntId': CogParent3,
                'pos': Point3(0, 0, 0)},
               BattleCellId4: {'parentEntId': CogParent4,
                'pos': Point3(0, 0, 0)}}
CogData = [{'parentEntId': CogParent,
  'boss': 0,
  'level': 12,
  'battleCell': BattleCellId,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 13,
  'battleCell': BattleCellId,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 11,
  'battleCell': BattleCellId,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': 9,
  'battleCell': BattleCellId,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
   {'parentEntId': CogParent2,
    'boss': 0,
    'level': 12,
    'battleCell': BattleCellId2,
    'pos': Point3(-6, 0, 0),
    'h': 180,
    'behavior': 'stand',
    'path': None,
    'skeleton': 1},
   {'parentEntId': CogParent2,
    'boss': 0,
    'level': 13,
    'battleCell': BattleCellId2,
    'pos': Point3(-2, 0, 0),
    'h': 180,
    'behavior': 'stand',
    'path': None,
    'skeleton': 0},
   {'parentEntId': CogParent2,
    'boss': 0,
    'level': 11,
    'battleCell': BattleCellId2,
    'pos': Point3(2, 0, 0),
    'h': 180,
    'behavior': 'stand',
    'path': None,
    'skeleton': 0},
   {'parentEntId': CogParent2,
    'boss': 0,
    'level': 9,
    'battleCell': BattleCellId2,
    'pos': Point3(6, 0, 0),
    'h': 180,
    'behavior': 'stand',
    'path': None,
    'skeleton': 0},
   {'parentEntId': CogParent3,
    'boss': 0,
    'level': 12,
    'battleCell': BattleCellId3,
    'pos': Point3(-6, 0, 0),
    'h': 180,
    'behavior': 'stand',
    'path': None,
    'skeleton': 1},
   {'parentEntId': CogParent3,
    'boss': 0,
    'level': 13,
    'battleCell': BattleCellId3,
    'pos': Point3(-2, 0, 0),
    'h': 180,
    'behavior': 'stand',
    'path': None,
    'skeleton': 0},
   {'parentEntId': CogParent3,
    'boss': 0,
    'level': 11,
    'battleCell': BattleCellId3,
    'pos': Point3(2, 0, 0),
    'h': 180,
    'behavior': 'stand',
    'path': None,
    'skeleton': 0},
   {'parentEntId': CogParent3,
    'boss': 0,
    'level': 9,
    'battleCell': BattleCellId3,
    'pos': Point3(6, 0, 0),
    'h': 180,
    'behavior': 'stand',
    'path': None,
    'skeleton': 0},
   {'parentEntId': CogParent4,
    'boss': 0,
    'level': 12,
    'battleCell': BattleCellId4,
    'pos': Point3(-6, 0, 0),
    'h': 180,
    'behavior': 'stand',
    'path': None,
    'skeleton': 1},
   {'parentEntId': CogParent4,
    'boss': 0,
    'level': 13,
    'battleCell': BattleCellId4,
    'pos': Point3(-2, 0, 0),
    'h': 180,
    'behavior': 'stand',
    'path': None,
    'skeleton': 0},
   {'parentEntId': CogParent4,
    'boss': 0,
    'level': 11,
    'battleCell': BattleCellId4,
    'pos': Point3(2, 0, 0),
    'h': 180,
    'behavior': 'stand',
    'path': None,
    'skeleton': 0},
   {'parentEntId': CogParent4,
    'boss': 0,
    'level': 9,
    'battleCell': BattleCellId4,
    'pos': Point3(6, 0, 0),
    'h': 180,
    'behavior': 'stand',
    'path': None,
    'skeleton': 0}]
ReserveCogData = []
