from toontown.quest.Quests import *
import random

"""
(TreasureQuest,
        ToontownGlobals.ToontownCentral,
        5),

(TreasureQuest,
        ToontownGlobals.SillyStreet,
        1,
        1),

(TreasureQuest,
        ToontownGlobals.SillyStreet,
        1,
        1),

(BuildingFloorsQuest,
         Anywhere,
         4,
         's'),

"""

QuestDict = {
  16104: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 3, Any),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
 16105: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 3, Any),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
 16106: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 3, Any),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
 16107: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 3, Any),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
 16108: (TT_TIER,
         Start,
         (TreasureQuest,
          ToontownGlobals.SillyStreet,
          1,
          1),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
16109: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 2, 'f'),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
16110: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 2, 'bf'),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
16111: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 2, 'cc'),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
 16112: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 2, 'cc'),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16300: (TT_TIER + 1, Start, (VisitQuest,), ToonHQ, 2128, NA, 16301, TTLocalizer.QuestDialogDict[16300]),
  16301: (TT_TIER + 1, Cont, (FishQuest, ToontownGlobals.SillyStreet, 1, 4), 2128, 2128, NA, 16302, TTLocalizer.QuestDialogDict[16301]),
  16302: (TT_TIER + 1, Cont, (DeliverItemQuest, 7), 2128, ToonHQ, 100, NA, TTLocalizer.QuestDialogDict[16302]),

  16310: (TT_TIER + 1, Start, (VisitQuest,), ToonHQ, 2005, NA, 16311, DefaultDialog),
  16311: (TT_TIER + 1, Cont, (RecoverItemQuest, Anywhere, 1, 4, VeryEasy, Any), 2005, 2005, NA, 16312, DefaultDialog),
  16312: (TT_TIER + 1, Cont, (TreasureQuest, ToontownGlobals.SillyStreet, 1, 1), 2005, 2005, 100, NA, DefaultDialog)
}

#2005
#2128 (VisitQuest,), (DeliverItemQuest, 1000),