from toontown.quest.Quests import *

"""
(TreasureQuest,
        ToontownGlobals.ToontownCentral,
        5),

(TreasureQuest,
        ToontownGlobals.SillyStreet,
        1,
        1),

(TreasureQuest,
        ToontownGlobals.SillyStreet,
        1,
        1),

(BuildingFloorsQuest,
         Anywhere,
         4,
         's'),

"""

QuestDict = {
   15000: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 2, 'cc'),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  15010: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 2, 'f'),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  15020: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 2, 'bf'),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  15030: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 2, 'bar'),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  15040: (TT_TIER,
         Start,
          (CogTierQuest,
           Anywhere,
           2,
           1),
         Any,
         ToonHQ,
         101,
         NA,
         DefaultDialog),
  15050: (TT_TIER,
         Start,
         (CogTierQuest,
          Anywhere,
          1,
          2),
         Any,
         ToonHQ,
         101,
         NA,
         DefaultDialog),
  16000: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 2, 'sc'),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16100: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 4, Any),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16101: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 4, Any),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16102: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 4, Any),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16103: (TT_TIER,
         Start,
         (FishQuest,
          Anywhere,
          1,
          0),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16104: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 4, Any),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16105: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 4, Any),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16106: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 4, Any),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16107: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 1, 'pp'),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16108: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 1, 'b'),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16109: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 4, Any),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16110: (TT_TIER,
         Start,
         (CogQuest, Anywhere, 4, Any),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16111: (TT_TIER,
         Start,
         (CogVariousTracksQuest,
          Anywhere,
          2,
          'c',
          'm'),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16112: (TT_TIER,
         Start,
         (CogVariousTracksQuest,
          Anywhere,
          2,
          'l',
          'c'),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16113: (TT_TIER,
         Start,
         (CogVariousTracksQuest,
          Anywhere,
          2,
          's',
          'l'),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16114: (TT_TIER,
         Start,
         (CogVariousTracksQuest,
          Anywhere,
          2,
          'c',
          's'),
         Any,
         ToonHQ,
         100,
         NA,
         DefaultDialog),
  16300: (TT_TIER + 1, Start, (VisitQuest,), ToonHQ, 2128, NA, 16301, TTLocalizer.QuestDialogDict[16300]),
  16301: (TT_TIER + 1, Cont, (FishQuest, ToontownGlobals.SillyStreet, 1, 4), 2128, 2128, NA, 16302, TTLocalizer.QuestDialogDict[16301]),
  16302: (TT_TIER + 1, Cont, (DeliverItemQuest, 7), 2128, ToonHQ, 100, NA, TTLocalizer.QuestDialogDict[16302]),

  16310: (TT_TIER + 1, Start, (VisitQuest,), ToonHQ, 2005, NA, 16311, DefaultDialog),
  16311: (TT_TIER + 1, Cont, (RecoverItemQuest, Anywhere, 1, 4, VeryEasy, Any), 2005, 2005, NA, 16312, DefaultDialog),
  16312: (TT_TIER + 1, Cont, (TreasureQuest, ToontownGlobals.SillyStreet, 1, 1), 2005, 2005, 100, NA, DefaultDialog)
}

#2005
#2128 (VisitQuest,), (DeliverItemQuest, 1000),